// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pa.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Commands send from Device to SiteWhere
type DeviceEvent_Command int32

const (
	DeviceEvent_SendRegistration    DeviceEvent_Command = 0
	DeviceEvent_SendAcknowledgement DeviceEvent_Command = 1
	DeviceEvent_SendLocation        DeviceEvent_Command = 2
	DeviceEvent_SendAlert           DeviceEvent_Command = 3
	DeviceEvent_SendMeasurement     DeviceEvent_Command = 4
	DeviceEvent_CreateStream        DeviceEvent_Command = 5
)

var DeviceEvent_Command_name = map[int32]string{
	0: "SendRegistration",
	1: "SendAcknowledgement",
	2: "SendLocation",
	3: "SendAlert",
	4: "SendMeasurement",
	5: "CreateStream",
}

var DeviceEvent_Command_value = map[string]int32{
	"SendRegistration":    0,
	"SendAcknowledgement": 1,
	"SendLocation":        2,
	"SendAlert":           3,
	"SendMeasurement":     4,
	"CreateStream":        5,
}

func (x DeviceEvent_Command) String() string {
	return proto.EnumName(DeviceEvent_Command_name, int32(x))
}

func (DeviceEvent_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 0}
}

// Alert Level
type DeviceEvent_AlertLevel int32

const (
	DeviceEvent_Info     DeviceEvent_AlertLevel = 0
	DeviceEvent_Warning  DeviceEvent_AlertLevel = 1
	DeviceEvent_Error    DeviceEvent_AlertLevel = 2
	DeviceEvent_Critical DeviceEvent_AlertLevel = 3
)

var DeviceEvent_AlertLevel_name = map[int32]string{
	0: "Info",
	1: "Warning",
	2: "Error",
	3: "Critical",
}

var DeviceEvent_AlertLevel_value = map[string]int32{
	"Info":     0,
	"Warning":  1,
	"Error":    2,
	"Critical": 3,
}

func (x DeviceEvent_AlertLevel) String() string {
	return proto.EnumName(DeviceEvent_AlertLevel_name, int32(x))
}

func (DeviceEvent_AlertLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 1}
}

// Commands sent from SiteWhere to a device.
type Device_Command int32

const (
	Device_REGISTRATION_ACK           Device_Command = 0
	Device_DEVICE_STREAM_ACK          Device_Command = 1
	Device_RECEIVE_DEVICE_STREAM_DATA Device_Command = 2
)

var Device_Command_name = map[int32]string{
	0: "REGISTRATION_ACK",
	1: "DEVICE_STREAM_ACK",
	2: "RECEIVE_DEVICE_STREAM_DATA",
}

var Device_Command_value = map[string]int32{
	"REGISTRATION_ACK":           0,
	"DEVICE_STREAM_ACK":          1,
	"RECEIVE_DEVICE_STREAM_DATA": 2,
}

func (x Device_Command) String() string {
	return proto.EnumName(Device_Command_name, int32(x))
}

func (Device_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 0}
}

// Enumeration of registation state responses.
type Device_RegistrationAckState int32

const (
	Device_NEW_REGISTRATION   Device_RegistrationAckState = 0
	Device_ALREADY_REGISTERED Device_RegistrationAckState = 1
	Device_REGISTRATION_ERROR Device_RegistrationAckState = 2
)

var Device_RegistrationAckState_name = map[int32]string{
	0: "NEW_REGISTRATION",
	1: "ALREADY_REGISTERED",
	2: "REGISTRATION_ERROR",
}

var Device_RegistrationAckState_value = map[string]int32{
	"NEW_REGISTRATION":   0,
	"ALREADY_REGISTERED": 1,
	"REGISTRATION_ERROR": 2,
}

func (x Device_RegistrationAckState) String() string {
	return proto.EnumName(Device_RegistrationAckState_name, int32(x))
}

func (Device_RegistrationAckState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 1}
}

type Device_RegistrationAckError int32

const (
	Device_INVALID_SPECIFICATION   Device_RegistrationAckError = 0
	Device_SITE_TOKEN_REQUIRED     Device_RegistrationAckError = 1
	Device_NEW_DEVICES_NOT_ALLOWED Device_RegistrationAckError = 2
)

var Device_RegistrationAckError_name = map[int32]string{
	0: "INVALID_SPECIFICATION",
	1: "SITE_TOKEN_REQUIRED",
	2: "NEW_DEVICES_NOT_ALLOWED",
}

var Device_RegistrationAckError_value = map[string]int32{
	"INVALID_SPECIFICATION":   0,
	"SITE_TOKEN_REQUIRED":     1,
	"NEW_DEVICES_NOT_ALLOWED": 2,
}

func (x Device_RegistrationAckError) String() string {
	return proto.EnumName(Device_RegistrationAckError_name, int32(x))
}

func (Device_RegistrationAckError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 2}
}

// Enumeration of device stream creation responses.
type Device_DeviceStreamAckState int32

const (
	Device_STREAM_CREATED Device_DeviceStreamAckState = 0
	Device_STREAM_EXISTS  Device_DeviceStreamAckState = 1
	Device_STREAM_FAILED  Device_DeviceStreamAckState = 2
)

var Device_DeviceStreamAckState_name = map[int32]string{
	0: "STREAM_CREATED",
	1: "STREAM_EXISTS",
	2: "STREAM_FAILED",
}

var Device_DeviceStreamAckState_value = map[string]int32{
	"STREAM_CREATED": 0,
	"STREAM_EXISTS":  1,
	"STREAM_FAILED":  2,
}

func (x Device_DeviceStreamAckState) String() string {
	return proto.EnumName(Device_DeviceStreamAckState_name, int32(x))
}

func (Device_DeviceStreamAckState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 3}
}

// Optional string value.
type GOptionalString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GOptionalString) Reset()         { *m = GOptionalString{} }
func (m *GOptionalString) String() string { return proto.CompactTextString(m) }
func (*GOptionalString) ProtoMessage()    {}
func (*GOptionalString) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{0}
}

func (m *GOptionalString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GOptionalString.Unmarshal(m, b)
}
func (m *GOptionalString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GOptionalString.Marshal(b, m, deterministic)
}
func (m *GOptionalString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GOptionalString.Merge(m, src)
}
func (m *GOptionalString) XXX_Size() int {
	return xxx_messageInfo_GOptionalString.Size(m)
}
func (m *GOptionalString) XXX_DiscardUnknown() {
	xxx_messageInfo_GOptionalString.DiscardUnknown(m)
}

var xxx_messageInfo_GOptionalString proto.InternalMessageInfo

func (m *GOptionalString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Optional boolean value.
type GOptionalBoolean struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GOptionalBoolean) Reset()         { *m = GOptionalBoolean{} }
func (m *GOptionalBoolean) String() string { return proto.CompactTextString(m) }
func (*GOptionalBoolean) ProtoMessage()    {}
func (*GOptionalBoolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{1}
}

func (m *GOptionalBoolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GOptionalBoolean.Unmarshal(m, b)
}
func (m *GOptionalBoolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GOptionalBoolean.Marshal(b, m, deterministic)
}
func (m *GOptionalBoolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GOptionalBoolean.Merge(m, src)
}
func (m *GOptionalBoolean) XXX_Size() int {
	return xxx_messageInfo_GOptionalBoolean.Size(m)
}
func (m *GOptionalBoolean) XXX_DiscardUnknown() {
	xxx_messageInfo_GOptionalBoolean.DiscardUnknown(m)
}

var xxx_messageInfo_GOptionalBoolean proto.InternalMessageInfo

func (m *GOptionalBoolean) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

// Optional double value.
type GOptionalDouble struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GOptionalDouble) Reset()         { *m = GOptionalDouble{} }
func (m *GOptionalDouble) String() string { return proto.CompactTextString(m) }
func (*GOptionalDouble) ProtoMessage()    {}
func (*GOptionalDouble) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{2}
}

func (m *GOptionalDouble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GOptionalDouble.Unmarshal(m, b)
}
func (m *GOptionalDouble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GOptionalDouble.Marshal(b, m, deterministic)
}
func (m *GOptionalDouble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GOptionalDouble.Merge(m, src)
}
func (m *GOptionalDouble) XXX_Size() int {
	return xxx_messageInfo_GOptionalDouble.Size(m)
}
func (m *GOptionalDouble) XXX_DiscardUnknown() {
	xxx_messageInfo_GOptionalDouble.DiscardUnknown(m)
}

var xxx_messageInfo_GOptionalDouble proto.InternalMessageInfo

func (m *GOptionalDouble) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Optional fixed64 value.
type GOptionalFixed64 struct {
	Value                uint64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GOptionalFixed64) Reset()         { *m = GOptionalFixed64{} }
func (m *GOptionalFixed64) String() string { return proto.CompactTextString(m) }
func (*GOptionalFixed64) ProtoMessage()    {}
func (*GOptionalFixed64) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{3}
}

func (m *GOptionalFixed64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GOptionalFixed64.Unmarshal(m, b)
}
func (m *GOptionalFixed64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GOptionalFixed64.Marshal(b, m, deterministic)
}
func (m *GOptionalFixed64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GOptionalFixed64.Merge(m, src)
}
func (m *GOptionalFixed64) XXX_Size() int {
	return xxx_messageInfo_GOptionalFixed64.Size(m)
}
func (m *GOptionalFixed64) XXX_DiscardUnknown() {
	xxx_messageInfo_GOptionalFixed64.DiscardUnknown(m)
}

var xxx_messageInfo_GOptionalFixed64 proto.InternalMessageInfo

func (m *GOptionalFixed64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DeviceEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceEvent) Write(p []byte) (n int, err error) {
	panic("implement me")
}

func (m *DeviceEvent) Reset()         { *m = DeviceEvent{} }
func (m *DeviceEvent) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent) ProtoMessage()    {}
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4}
}

func (m *DeviceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent.Unmarshal(m, b)
}
func (m *DeviceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent.Marshal(b, m, deterministic)
}
func (m *DeviceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent.Merge(m, src)
}
func (m *DeviceEvent) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent.Size(m)
}
func (m *DeviceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent proto.InternalMessageInfo

// Header contains the command, device token and originator.
type DeviceEvent_Header struct {
	Command              DeviceEvent_Command `protobuf:"varint,1,opt,name=command,proto3,enum=proto.DeviceEvent_Command" json:"command,omitempty"`
	DeviceToken          *GOptionalString    `protobuf:"bytes,2,opt,name=deviceToken,proto3" json:"deviceToken,omitempty"`
	Originator           *GOptionalString    `protobuf:"bytes,3,opt,name=originator,proto3" json:"originator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeviceEvent_Header) Reset()         { *m = DeviceEvent_Header{} }
func (m *DeviceEvent_Header) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_Header) ProtoMessage()    {}
func (*DeviceEvent_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 0}
}

func (m *DeviceEvent_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_Header.Unmarshal(m, b)
}
func (m *DeviceEvent_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_Header.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_Header.Merge(m, src)
}
func (m *DeviceEvent_Header) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_Header.Size(m)
}
func (m *DeviceEvent_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_Header.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_Header proto.InternalMessageInfo

func (m *DeviceEvent_Header) GetCommand() DeviceEvent_Command {
	if m != nil {
		return m.Command
	}
	return DeviceEvent_SendRegistration
}

func (m *DeviceEvent_Header) GetDeviceToken() *GOptionalString {
	if m != nil {
		return m.DeviceToken
	}
	return nil
}

func (m *DeviceEvent_Header) GetOriginator() *GOptionalString {
	if m != nil {
		return m.Originator
	}
	return nil
}

// Fields for requesting a device registration.
type DeviceEvent_DeviceRegistrationRequest struct {
	DeviceTypeToken      *GOptionalString  `protobuf:"bytes,1,opt,name=deviceTypeToken,proto3" json:"deviceTypeToken,omitempty"`
	CustomerToken        *GOptionalString  `protobuf:"bytes,2,opt,name=customerToken,proto3" json:"customerToken,omitempty"`
	AreaToken            *GOptionalString  `protobuf:"bytes,3,opt,name=areaToken,proto3" json:"areaToken,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceEvent_DeviceRegistrationRequest) Reset()         { *m = DeviceEvent_DeviceRegistrationRequest{} }
func (m *DeviceEvent_DeviceRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceRegistrationRequest) ProtoMessage()    {}
func (*DeviceEvent_DeviceRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 1}
}

func (m *DeviceEvent_DeviceRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest.Merge(m, src)
}
func (m *DeviceEvent_DeviceRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest.Size(m)
}
func (m *DeviceEvent_DeviceRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceRegistrationRequest proto.InternalMessageInfo

func (m *DeviceEvent_DeviceRegistrationRequest) GetDeviceTypeToken() *GOptionalString {
	if m != nil {
		return m.DeviceTypeToken
	}
	return nil
}

func (m *DeviceEvent_DeviceRegistrationRequest) GetCustomerToken() *GOptionalString {
	if m != nil {
		return m.CustomerToken
	}
	return nil
}

func (m *DeviceEvent_DeviceRegistrationRequest) GetAreaToken() *GOptionalString {
	if m != nil {
		return m.AreaToken
	}
	return nil
}

func (m *DeviceEvent_DeviceRegistrationRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Device Ack message fields
type DeviceEvent_DeviceAcknowledge struct {
	Message              *GOptionalString `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeviceEvent_DeviceAcknowledge) Reset()         { *m = DeviceEvent_DeviceAcknowledge{} }
func (m *DeviceEvent_DeviceAcknowledge) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceAcknowledge) ProtoMessage()    {}
func (*DeviceEvent_DeviceAcknowledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 2}
}

func (m *DeviceEvent_DeviceAcknowledge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceAcknowledge.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceAcknowledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceAcknowledge.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceAcknowledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceAcknowledge.Merge(m, src)
}
func (m *DeviceEvent_DeviceAcknowledge) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceAcknowledge.Size(m)
}
func (m *DeviceEvent_DeviceAcknowledge) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceAcknowledge.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceAcknowledge proto.InternalMessageInfo

func (m *DeviceEvent_DeviceAcknowledge) GetMessage() *GOptionalString {
	if m != nil {
		return m.Message
	}
	return nil
}

// Device Location fields
type DeviceEvent_DeviceLocation struct {
	Latitude             *GOptionalDouble  `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            *GOptionalDouble  `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation            *GOptionalDouble  `protobuf:"bytes,3,opt,name=elevation,proto3" json:"elevation,omitempty"`
	EventDate            *GOptionalFixed64 `protobuf:"bytes,4,opt,name=eventDate,proto3" json:"eventDate,omitempty"`
	UpdateState          *GOptionalBoolean `protobuf:"bytes,5,opt,name=updateState,proto3" json:"updateState,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceEvent_DeviceLocation) Reset()         { *m = DeviceEvent_DeviceLocation{} }
func (m *DeviceEvent_DeviceLocation) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceLocation) ProtoMessage()    {}
func (*DeviceEvent_DeviceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 3}
}

func (m *DeviceEvent_DeviceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceLocation.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceLocation.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceLocation.Merge(m, src)
}
func (m *DeviceEvent_DeviceLocation) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceLocation.Size(m)
}
func (m *DeviceEvent_DeviceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceLocation proto.InternalMessageInfo

func (m *DeviceEvent_DeviceLocation) GetLatitude() *GOptionalDouble {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *DeviceEvent_DeviceLocation) GetLongitude() *GOptionalDouble {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *DeviceEvent_DeviceLocation) GetElevation() *GOptionalDouble {
	if m != nil {
		return m.Elevation
	}
	return nil
}

func (m *DeviceEvent_DeviceLocation) GetEventDate() *GOptionalFixed64 {
	if m != nil {
		return m.EventDate
	}
	return nil
}

func (m *DeviceEvent_DeviceLocation) GetUpdateState() *GOptionalBoolean {
	if m != nil {
		return m.UpdateState
	}
	return nil
}

func (m *DeviceEvent_DeviceLocation) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Device Alert fields
type DeviceEvent_DeviceAlert struct {
	AlertType            *GOptionalString       `protobuf:"bytes,1,opt,name=alertType,proto3" json:"alertType,omitempty"`
	Level                DeviceEvent_AlertLevel `protobuf:"varint,2,opt,name=level,proto3,enum=proto.DeviceEvent_AlertLevel" json:"level,omitempty"`
	AlertMessage         *GOptionalString       `protobuf:"bytes,3,opt,name=alertMessage,proto3" json:"alertMessage,omitempty"`
	EventDate            *GOptionalFixed64      `protobuf:"bytes,4,opt,name=eventDate,proto3" json:"eventDate,omitempty"`
	UpdateState          *GOptionalBoolean      `protobuf:"bytes,5,opt,name=updateState,proto3" json:"updateState,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeviceEvent_DeviceAlert) Reset()         { *m = DeviceEvent_DeviceAlert{} }
func (m *DeviceEvent_DeviceAlert) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceAlert) ProtoMessage()    {}
func (*DeviceEvent_DeviceAlert) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 4}
}

func (m *DeviceEvent_DeviceAlert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceAlert.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceAlert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceAlert.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceAlert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceAlert.Merge(m, src)
}
func (m *DeviceEvent_DeviceAlert) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceAlert.Size(m)
}
func (m *DeviceEvent_DeviceAlert) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceAlert.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceAlert proto.InternalMessageInfo

func (m *DeviceEvent_DeviceAlert) GetAlertType() *GOptionalString {
	if m != nil {
		return m.AlertType
	}
	return nil
}

func (m *DeviceEvent_DeviceAlert) GetLevel() DeviceEvent_AlertLevel {
	if m != nil {
		return m.Level
	}
	return DeviceEvent_Info
}

func (m *DeviceEvent_DeviceAlert) GetAlertMessage() *GOptionalString {
	if m != nil {
		return m.AlertMessage
	}
	return nil
}

func (m *DeviceEvent_DeviceAlert) GetEventDate() *GOptionalFixed64 {
	if m != nil {
		return m.EventDate
	}
	return nil
}

func (m *DeviceEvent_DeviceAlert) GetUpdateState() *GOptionalBoolean {
	if m != nil {
		return m.UpdateState
	}
	return nil
}

func (m *DeviceEvent_DeviceAlert) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Device Measurement
type DeviceEvent_DeviceMeasurement struct {
	MeasurementName      *GOptionalString  `protobuf:"bytes,1,opt,name=measurementName,proto3" json:"measurementName,omitempty"`
	MeasurementValue     *GOptionalDouble  `protobuf:"bytes,2,opt,name=measurementValue,proto3" json:"measurementValue,omitempty"`
	EventDate            *GOptionalFixed64 `protobuf:"bytes,3,opt,name=eventDate,proto3" json:"eventDate,omitempty"`
	UpdateState          *GOptionalBoolean `protobuf:"bytes,4,opt,name=updateState,proto3" json:"updateState,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceEvent_DeviceMeasurement) Reset()         { *m = DeviceEvent_DeviceMeasurement{} }
func (m *DeviceEvent_DeviceMeasurement) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceMeasurement) ProtoMessage()    {}
func (*DeviceEvent_DeviceMeasurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 5}
}

func (m *DeviceEvent_DeviceMeasurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceMeasurement.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceMeasurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceMeasurement.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceMeasurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceMeasurement.Merge(m, src)
}
func (m *DeviceEvent_DeviceMeasurement) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceMeasurement.Size(m)
}
func (m *DeviceEvent_DeviceMeasurement) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceMeasurement.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceMeasurement proto.InternalMessageInfo

func (m *DeviceEvent_DeviceMeasurement) GetMeasurementName() *GOptionalString {
	if m != nil {
		return m.MeasurementName
	}
	return nil
}

func (m *DeviceEvent_DeviceMeasurement) GetMeasurementValue() *GOptionalDouble {
	if m != nil {
		return m.MeasurementValue
	}
	return nil
}

func (m *DeviceEvent_DeviceMeasurement) GetEventDate() *GOptionalFixed64 {
	if m != nil {
		return m.EventDate
	}
	return nil
}

func (m *DeviceEvent_DeviceMeasurement) GetUpdateState() *GOptionalBoolean {
	if m != nil {
		return m.UpdateState
	}
	return nil
}

func (m *DeviceEvent_DeviceMeasurement) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Create a device stream.
type DeviceEvent_DeviceStream struct {
	StreamId             *GOptionalString  `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	ContentType          *GOptionalString  `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceEvent_DeviceStream) Reset()         { *m = DeviceEvent_DeviceStream{} }
func (m *DeviceEvent_DeviceStream) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceStream) ProtoMessage()    {}
func (*DeviceEvent_DeviceStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 6}
}

func (m *DeviceEvent_DeviceStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceStream.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceStream.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceStream.Merge(m, src)
}
func (m *DeviceEvent_DeviceStream) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceStream.Size(m)
}
func (m *DeviceEvent_DeviceStream) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceStream.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceStream proto.InternalMessageInfo

func (m *DeviceEvent_DeviceStream) GetStreamId() *GOptionalString {
	if m != nil {
		return m.StreamId
	}
	return nil
}

func (m *DeviceEvent_DeviceStream) GetContentType() *GOptionalString {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *DeviceEvent_DeviceStream) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// A chunk of streaming data.
type DeviceEvent_DeviceStreamData struct {
	DeviceToken          *GOptionalString  `protobuf:"bytes,1,opt,name=deviceToken,proto3" json:"deviceToken,omitempty"`
	StreamId             *GOptionalString  `protobuf:"bytes,2,opt,name=streamId,proto3" json:"streamId,omitempty"`
	SequenceNumber       *GOptionalFixed64 `protobuf:"bytes,3,opt,name=sequenceNumber,proto3" json:"sequenceNumber,omitempty"`
	Data                 []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	EventDate            *GOptionalFixed64 `protobuf:"bytes,5,opt,name=eventDate,proto3" json:"eventDate,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceEvent_DeviceStreamData) Reset()         { *m = DeviceEvent_DeviceStreamData{} }
func (m *DeviceEvent_DeviceStreamData) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent_DeviceStreamData) ProtoMessage()    {}
func (*DeviceEvent_DeviceStreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{4, 7}
}

func (m *DeviceEvent_DeviceStreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent_DeviceStreamData.Unmarshal(m, b)
}
func (m *DeviceEvent_DeviceStreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent_DeviceStreamData.Marshal(b, m, deterministic)
}
func (m *DeviceEvent_DeviceStreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent_DeviceStreamData.Merge(m, src)
}
func (m *DeviceEvent_DeviceStreamData) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent_DeviceStreamData.Size(m)
}
func (m *DeviceEvent_DeviceStreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent_DeviceStreamData.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent_DeviceStreamData proto.InternalMessageInfo

func (m *DeviceEvent_DeviceStreamData) GetDeviceToken() *GOptionalString {
	if m != nil {
		return m.DeviceToken
	}
	return nil
}

func (m *DeviceEvent_DeviceStreamData) GetStreamId() *GOptionalString {
	if m != nil {
		return m.StreamId
	}
	return nil
}

func (m *DeviceEvent_DeviceStreamData) GetSequenceNumber() *GOptionalFixed64 {
	if m != nil {
		return m.SequenceNumber
	}
	return nil
}

func (m *DeviceEvent_DeviceStreamData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DeviceEvent_DeviceStreamData) GetEventDate() *GOptionalFixed64 {
	if m != nil {
		return m.EventDate
	}
	return nil
}

func (m *DeviceEvent_DeviceStreamData) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Commands sent from SiteWhere to a device.
type Device struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

// Header contains the command and originator.
type Device_Header struct {
	Command              Device_Command   `protobuf:"varint,1,opt,name=command,proto3,enum=proto.Device_Command" json:"command,omitempty"`
	Originator           *GOptionalString `protobuf:"bytes,2,opt,name=originator,proto3" json:"originator,omitempty"`
	NestedPath           *GOptionalString `protobuf:"bytes,3,opt,name=nestedPath,proto3" json:"nestedPath,omitempty"`
	NestedSpec           *GOptionalString `protobuf:"bytes,4,opt,name=nestedSpec,proto3" json:"nestedSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Device_Header) Reset()         { *m = Device_Header{} }
func (m *Device_Header) String() string { return proto.CompactTextString(m) }
func (*Device_Header) ProtoMessage()    {}
func (*Device_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 0}
}

func (m *Device_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device_Header.Unmarshal(m, b)
}
func (m *Device_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device_Header.Marshal(b, m, deterministic)
}
func (m *Device_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device_Header.Merge(m, src)
}
func (m *Device_Header) XXX_Size() int {
	return xxx_messageInfo_Device_Header.Size(m)
}
func (m *Device_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Device_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Device_Header proto.InternalMessageInfo

func (m *Device_Header) GetCommand() Device_Command {
	if m != nil {
		return m.Command
	}
	return Device_REGISTRATION_ACK
}

func (m *Device_Header) GetOriginator() *GOptionalString {
	if m != nil {
		return m.Originator
	}
	return nil
}

func (m *Device_Header) GetNestedPath() *GOptionalString {
	if m != nil {
		return m.NestedPath
	}
	return nil
}

func (m *Device_Header) GetNestedSpec() *GOptionalString {
	if m != nil {
		return m.NestedSpec
	}
	return nil
}

// Acknowledges registration.
type Device_RegistrationAck struct {
	State                Device_RegistrationAckState `protobuf:"varint,1,opt,name=state,proto3,enum=proto.Device_RegistrationAckState" json:"state,omitempty"`
	ErrorType            Device_RegistrationAckError `protobuf:"varint,2,opt,name=errorType,proto3,enum=proto.Device_RegistrationAckError" json:"errorType,omitempty"`
	ErrorMessage         *GOptionalString            `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Device_RegistrationAck) Reset()         { *m = Device_RegistrationAck{} }
func (m *Device_RegistrationAck) String() string { return proto.CompactTextString(m) }
func (*Device_RegistrationAck) ProtoMessage()    {}
func (*Device_RegistrationAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 1}
}

func (m *Device_RegistrationAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device_RegistrationAck.Unmarshal(m, b)
}
func (m *Device_RegistrationAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device_RegistrationAck.Marshal(b, m, deterministic)
}
func (m *Device_RegistrationAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device_RegistrationAck.Merge(m, src)
}
func (m *Device_RegistrationAck) XXX_Size() int {
	return xxx_messageInfo_Device_RegistrationAck.Size(m)
}
func (m *Device_RegistrationAck) XXX_DiscardUnknown() {
	xxx_messageInfo_Device_RegistrationAck.DiscardUnknown(m)
}

var xxx_messageInfo_Device_RegistrationAck proto.InternalMessageInfo

func (m *Device_RegistrationAck) GetState() Device_RegistrationAckState {
	if m != nil {
		return m.State
	}
	return Device_NEW_REGISTRATION
}

func (m *Device_RegistrationAck) GetErrorType() Device_RegistrationAckError {
	if m != nil {
		return m.ErrorType
	}
	return Device_INVALID_SPECIFICATION
}

func (m *Device_RegistrationAck) GetErrorMessage() *GOptionalString {
	if m != nil {
		return m.ErrorMessage
	}
	return nil
}

// Acknowledges creation of device stream.
type Device_DeviceStreamAck struct {
	StreamId             *GOptionalString            `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	State                Device_DeviceStreamAckState `protobuf:"varint,2,opt,name=state,proto3,enum=proto.Device_DeviceStreamAckState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Device_DeviceStreamAck) Reset()         { *m = Device_DeviceStreamAck{} }
func (m *Device_DeviceStreamAck) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceStreamAck) ProtoMessage()    {}
func (*Device_DeviceStreamAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edce6c8ca0ee4bf, []int{5, 2}
}

func (m *Device_DeviceStreamAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device_DeviceStreamAck.Unmarshal(m, b)
}
func (m *Device_DeviceStreamAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device_DeviceStreamAck.Marshal(b, m, deterministic)
}
func (m *Device_DeviceStreamAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device_DeviceStreamAck.Merge(m, src)
}
func (m *Device_DeviceStreamAck) XXX_Size() int {
	return xxx_messageInfo_Device_DeviceStreamAck.Size(m)
}
func (m *Device_DeviceStreamAck) XXX_DiscardUnknown() {
	xxx_messageInfo_Device_DeviceStreamAck.DiscardUnknown(m)
}

var xxx_messageInfo_Device_DeviceStreamAck proto.InternalMessageInfo

func (m *Device_DeviceStreamAck) GetStreamId() *GOptionalString {
	if m != nil {
		return m.StreamId
	}
	return nil
}

func (m *Device_DeviceStreamAck) GetState() Device_DeviceStreamAckState {
	if m != nil {
		return m.State
	}
	return Device_STREAM_CREATED
}

func init() {
	proto.RegisterEnum("proto.DeviceEvent_Command", DeviceEvent_Command_name, DeviceEvent_Command_value)
	proto.RegisterEnum("proto.DeviceEvent_AlertLevel", DeviceEvent_AlertLevel_name, DeviceEvent_AlertLevel_value)
	proto.RegisterEnum("proto.Device_Command", Device_Command_name, Device_Command_value)
	proto.RegisterEnum("proto.Device_RegistrationAckState", Device_RegistrationAckState_name, Device_RegistrationAckState_value)
	proto.RegisterEnum("proto.Device_RegistrationAckError", Device_RegistrationAckError_name, Device_RegistrationAckError_value)
	proto.RegisterEnum("proto.Device_DeviceStreamAckState", Device_DeviceStreamAckState_name, Device_DeviceStreamAckState_value)
	proto.RegisterType((*GOptionalString)(nil), "proto.GOptionalString")
	proto.RegisterType((*GOptionalBoolean)(nil), "proto.GOptionalBoolean")
	proto.RegisterType((*GOptionalDouble)(nil), "proto.GOptionalDouble")
	proto.RegisterType((*GOptionalFixed64)(nil), "proto.GOptionalFixed64")
	proto.RegisterType((*DeviceEvent)(nil), "proto.DeviceEvent")
	proto.RegisterType((*DeviceEvent_Header)(nil), "proto.DeviceEvent.Header")
	proto.RegisterType((*DeviceEvent_DeviceRegistrationRequest)(nil), "proto.DeviceEvent.DeviceRegistrationRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceRegistrationRequest.MetadataEntry")
	proto.RegisterType((*DeviceEvent_DeviceAcknowledge)(nil), "proto.DeviceEvent.DeviceAcknowledge")
	proto.RegisterType((*DeviceEvent_DeviceLocation)(nil), "proto.DeviceEvent.DeviceLocation")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceLocation.MetadataEntry")
	proto.RegisterType((*DeviceEvent_DeviceAlert)(nil), "proto.DeviceEvent.DeviceAlert")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceAlert.MetadataEntry")
	proto.RegisterType((*DeviceEvent_DeviceMeasurement)(nil), "proto.DeviceEvent.DeviceMeasurement")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceMeasurement.MetadataEntry")
	proto.RegisterType((*DeviceEvent_DeviceStream)(nil), "proto.DeviceEvent.DeviceStream")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceStream.MetadataEntry")
	proto.RegisterType((*DeviceEvent_DeviceStreamData)(nil), "proto.DeviceEvent.DeviceStreamData")
	proto.RegisterMapType((map[string]string)(nil), "proto.DeviceEvent.DeviceStreamData.MetadataEntry")
	proto.RegisterType((*Device)(nil), "proto.Device")
	proto.RegisterType((*Device_Header)(nil), "proto.Device.Header")
	proto.RegisterType((*Device_RegistrationAck)(nil), "proto.Device.RegistrationAck")
	proto.RegisterType((*Device_DeviceStreamAck)(nil), "proto.Device.DeviceStreamAck")
}

func init() { proto.RegisterFile("pa.proto", fileDescriptor_0edce6c8ca0ee4bf) }

var fileDescriptor_0edce6c8ca0ee4bf = []byte{
	// 1172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdf, 0x6e, 0x23, 0xb5,
	0x17, 0xee, 0x4c, 0x92, 0x36, 0x39, 0xe9, 0x1f, 0xaf, 0xb7, 0xdd, 0xed, 0xe6, 0xa7, 0x1f, 0xaa,
	0x72, 0x43, 0x2f, 0xa0, 0x0b, 0xd9, 0xb2, 0x2a, 0x65, 0x25, 0x76, 0x36, 0x71, 0x77, 0x47, 0x4d,
	0x93, 0xe2, 0x84, 0x14, 0x24, 0xa4, 0xc8, 0x4d, 0x4c, 0x18, 0x75, 0x32, 0x13, 0x26, 0x4e, 0xa1,
	0x57, 0x70, 0xc1, 0x43, 0xf0, 0x0c, 0x08, 0x24, 0x5e, 0x83, 0x0b, 0x1e, 0x82, 0x1b, 0x9e, 0x03,
	0xd9, 0x33, 0xc9, 0x78, 0xd2, 0xa4, 0x09, 0x2b, 0x55, 0x5c, 0x25, 0x63, 0x7f, 0xdf, 0x39, 0x3e,
	0xe7, 0x3b, 0xc7, 0x3e, 0x90, 0x1d, 0xb0, 0x83, 0x41, 0xe0, 0x0b, 0x1f, 0x67, 0xd4, 0x4f, 0xf1,
	0x5d, 0xd8, 0x7a, 0x5d, 0x1f, 0x08, 0xc7, 0xf7, 0x98, 0xdb, 0x10, 0x81, 0xe3, 0xf5, 0xf0, 0x36,
	0x64, 0xae, 0x99, 0x3b, 0xe2, 0xbb, 0xc6, 0x9e, 0xb1, 0x9f, 0xa3, 0xe1, 0x47, 0x71, 0x1f, 0xd0,
	0x04, 0xf8, 0xca, 0xf7, 0x5d, 0xce, 0xbc, 0x24, 0x32, 0x3b, 0x46, 0xea, 0x26, 0x2b, 0xfe, 0xe8,
	0xd2, 0xe5, 0x49, 0xa0, 0x31, 0xcb, 0xe4, 0x89, 0xf3, 0x3d, 0xef, 0x3e, 0x3f, 0x4c, 0x22, 0x57,
	0xc7, 0xc8, 0x3f, 0x77, 0x20, 0x5f, 0xe1, 0xd7, 0x4e, 0x87, 0x93, 0x6b, 0xee, 0x89, 0xc2, 0xef,
	0x06, 0xac, 0xbe, 0xe1, 0xac, 0xcb, 0x03, 0x7c, 0x08, 0x6b, 0x1d, 0xbf, 0xdf, 0x67, 0x5e, 0x57,
	0x51, 0x36, 0x4b, 0x85, 0x30, 0xc0, 0x03, 0x0d, 0x7f, 0x50, 0x0e, 0x11, 0x74, 0x0c, 0xc5, 0x47,
	0x90, 0xef, 0xaa, 0xfd, 0xa6, 0x7f, 0xc5, 0xbd, 0x5d, 0x73, 0xcf, 0xd8, 0xcf, 0x97, 0x1e, 0x45,
	0xcc, 0xa9, 0x84, 0x50, 0x1d, 0x8a, 0x9f, 0x03, 0xf8, 0x81, 0xd3, 0x73, 0x3c, 0x26, 0xfc, 0x60,
	0x37, 0x75, 0x27, 0x51, 0x43, 0x16, 0xfe, 0x36, 0xe1, 0x49, 0x78, 0x24, 0xca, 0x7b, 0xce, 0x50,
	0x04, 0x4c, 0x42, 0x29, 0xff, 0x76, 0xc4, 0x87, 0x02, 0xbf, 0x84, 0xad, 0xc8, 0xc9, 0xcd, 0x20,
	0x3a, 0x93, 0x71, 0xa7, 0xe9, 0x69, 0x38, 0x7e, 0x01, 0x1b, 0x9d, 0xd1, 0x50, 0xf8, 0x7d, 0x1e,
	0x2c, 0x13, 0x53, 0x12, 0x8c, 0x0f, 0x21, 0xc7, 0x02, 0xce, 0x42, 0xe6, 0xdd, 0x41, 0xc5, 0x40,
	0xdc, 0x82, 0x6c, 0x9f, 0x0b, 0xd6, 0x65, 0x82, 0xed, 0xa6, 0xf7, 0x52, 0xfb, 0xf9, 0xd2, 0xf1,
	0x8c, 0xe4, 0xcf, 0x8d, 0xfa, 0xe0, 0x2c, 0x22, 0x13, 0x4f, 0x04, 0x37, 0x74, 0x62, 0xab, 0xf0,
	0x09, 0x6c, 0x24, 0xb6, 0x30, 0x82, 0xd4, 0x15, 0xbf, 0x89, 0x0a, 0x52, 0xfe, 0x8d, 0xeb, 0xc4,
	0xd4, 0x8a, 0xf4, 0xd8, 0x3c, 0x32, 0x0a, 0x04, 0x1e, 0x84, 0x1e, 0xad, 0xce, 0x95, 0xe7, 0x7f,
	0xe7, 0xf2, 0x6e, 0x8f, 0xe3, 0x0f, 0x60, 0xad, 0xcf, 0x87, 0x43, 0xd6, 0xe3, 0x0b, 0xf2, 0x3a,
	0x86, 0x15, 0x7e, 0x4d, 0xc1, 0x66, 0x68, 0xa7, 0xea, 0x77, 0xd4, 0xa9, 0x71, 0x09, 0xb2, 0x2e,
	0x13, 0x8e, 0x18, 0x75, 0xe7, 0x5a, 0x09, 0xeb, 0x9d, 0x4e, 0x70, 0x32, 0xb1, 0xae, 0xef, 0xf5,
	0x42, 0x92, 0x79, 0x27, 0x29, 0x06, 0x4a, 0x16, 0x77, 0xf9, 0xb5, 0x72, 0x3b, 0x4f, 0x8e, 0x31,
	0x6b, 0x02, 0xc4, 0x1f, 0x41, 0x8e, 0xcb, 0x8c, 0x57, 0x98, 0xe0, 0xbb, 0x69, 0xc5, 0x7a, 0x3c,
	0xcd, 0x8a, 0xfa, 0x8c, 0xc6, 0x48, 0xfc, 0x31, 0xe4, 0x47, 0x83, 0x2e, 0x13, 0xbc, 0x21, 0x24,
	0x31, 0x33, 0x9b, 0x18, 0xf5, 0x3c, 0xd5, 0xb1, 0xf8, 0x54, 0x2b, 0x80, 0x55, 0x55, 0x00, 0x4f,
	0xe7, 0x16, 0xc0, 0x38, 0x8d, 0xf7, 0xa3, 0xfa, 0x6f, 0xa9, 0xf1, 0x0d, 0x61, 0xb9, 0x3c, 0x10,
	0xaa, 0xa0, 0xe5, 0x1f, 0xd9, 0x20, 0x0b, 0x24, 0x8f, 0x81, 0xf8, 0x19, 0x64, 0x5c, 0x7e, 0xcd,
	0x5d, 0x65, 0x7f, 0xb3, 0xf4, 0xff, 0x19, 0xc1, 0x28, 0xf3, 0x55, 0x09, 0xa2, 0x21, 0x16, 0x1f,
	0xc3, 0xba, 0xb2, 0x70, 0x16, 0x15, 0xd8, 0xdd, 0xed, 0x93, 0xc0, 0xfe, 0x07, 0x92, 0xbd, 0xb9,
	0x25, 0xd9, 0x7b, 0x73, 0x25, 0x53, 0xb1, 0xde, 0x8f, 0x5e, 0x3f, 0xa7, 0xc6, 0x6d, 0x7a, 0xc6,
	0xd9, 0x70, 0x14, 0xf0, 0x3e, 0xf7, 0xd4, 0x35, 0xd8, 0x8f, 0x3f, 0x6b, 0xac, 0xbf, 0x48, 0xbb,
	0x69, 0x38, 0x7e, 0x05, 0x48, 0x5b, 0x6a, 0x4d, 0x9c, 0xcf, 0x6f, 0xa0, 0x5b, 0xf8, 0xa4, 0x28,
	0xa9, 0xb7, 0x15, 0x25, 0xfd, 0x2f, 0x44, 0xa9, 0x69, 0xa2, 0x64, 0x94, 0x28, 0xa5, 0xb9, 0xa2,
	0x68, 0xf9, 0xba, 0x1f, 0x69, 0x7e, 0x32, 0x61, 0x3d, 0x74, 0xd5, 0x10, 0x01, 0x67, 0x7d, 0x79,
	0xef, 0x0d, 0xd5, 0x3f, 0xbb, 0xbb, 0x40, 0x8e, 0x09, 0x4e, 0x3e, 0xb0, 0x1d, 0xdf, 0x13, 0xdc,
	0x0b, 0x3b, 0x70, 0xc1, 0x03, 0xab, 0x41, 0xb1, 0xad, 0xe5, 0x22, 0xa5, 0x72, 0xf1, 0xfe, 0xdc,
	0x5c, 0x84, 0x07, 0xbc, 0xb7, 0x0a, 0x45, 0xba, 0x97, 0x0a, 0x13, 0x6c, 0x7a, 0x6e, 0x30, 0x96,
	0x9f, 0x1b, 0xf4, 0x24, 0x9a, 0x4b, 0x26, 0xf1, 0x53, 0xd8, 0x1c, 0xca, 0xa7, 0xd2, 0xeb, 0xf0,
	0xda, 0xa8, 0x7f, 0xc9, 0x83, 0x45, 0xd5, 0x38, 0x05, 0xc7, 0x18, 0xd2, 0xd1, 0xe3, 0x6c, 0xec,
	0xaf, 0x53, 0xf5, 0x3f, 0x59, 0xdd, 0x99, 0xa5, 0xab, 0xfb, 0xec, 0xd6, 0xbd, 0xf1, 0xe1, 0x02,
	0x59, 0x64, 0xc2, 0xee, 0x45, 0x9a, 0xe2, 0x8f, 0x06, 0xac, 0x45, 0x23, 0x1d, 0xde, 0x06, 0xd4,
	0xe0, 0x5e, 0x57, 0x1f, 0x2f, 0xd0, 0x0a, 0x7e, 0x0c, 0x0f, 0xe5, 0xaa, 0x36, 0x02, 0xc8, 0x7e,
	0x41, 0x06, 0x46, 0xb0, 0x2e, 0x37, 0xc6, 0x8f, 0x11, 0x32, 0xf1, 0x06, 0xe4, 0x14, 0x54, 0xde,
	0x75, 0x28, 0x85, 0x1f, 0xc2, 0x96, 0xfc, 0xd4, 0xba, 0x0c, 0xa5, 0x25, 0xab, 0x1c, 0x70, 0xd5,
	0xae, 0x32, 0x32, 0x94, 0x29, 0xbe, 0x00, 0x88, 0x5f, 0x02, 0x9c, 0x85, 0xb4, 0xed, 0x7d, 0xed,
	0xa3, 0x15, 0x9c, 0x87, 0xb5, 0x0b, 0x16, 0x78, 0x8e, 0xd7, 0x43, 0x06, 0xce, 0x41, 0x86, 0x04,
	0x81, 0x1f, 0x20, 0x13, 0xaf, 0x43, 0xb6, 0x1c, 0x38, 0xc2, 0xe9, 0x30, 0x17, 0xa5, 0x8a, 0xbf,
	0xac, 0xc1, 0x6a, 0x98, 0xaa, 0xc2, 0x5f, 0xf1, 0x28, 0xfb, 0x74, 0x7a, 0x94, 0xdd, 0x49, 0x64,
	0xf8, 0xf6, 0x14, 0x9b, 0x9c, 0x45, 0xcd, 0x65, 0x67, 0x51, 0xc9, 0xf3, 0xf8, 0x50, 0xf0, 0xee,
	0x39, 0x13, 0xdf, 0x2c, 0x9a, 0x61, 0x63, 0x64, 0xcc, 0x6b, 0x0c, 0x78, 0x27, 0xba, 0xe0, 0x16,
	0xf0, 0x24, 0xb2, 0xf0, 0x87, 0x01, 0x5b, 0xba, 0x40, 0x56, 0xe7, 0x0a, 0x1f, 0x41, 0x66, 0xa8,
	0xee, 0xc9, 0x30, 0xd4, 0x62, 0x32, 0xd4, 0x29, 0xb4, 0xba, 0x25, 0x69, 0x48, 0xc0, 0x2f, 0x21,
	0xc7, 0x65, 0x56, 0x27, 0x17, 0xcb, 0x22, 0xb6, 0xd2, 0x80, 0xc6, 0x24, 0xf9, 0x62, 0xab, 0x8f,
	0x25, 0x5f, 0x6c, 0x1d, 0x5b, 0xf8, 0x01, 0xb6, 0xf4, 0x22, 0x97, 0xa1, 0xbc, 0xdd, 0xfd, 0x18,
	0x85, 0x3f, 0x33, 0x80, 0x29, 0x0f, 0x7a, 0xf8, 0xc5, 0x56, 0xa2, 0xf6, 0x29, 0x79, 0x6d, 0x37,
	0x9a, 0xd4, 0x6a, 0xda, 0xf5, 0x5a, 0xdb, 0x2a, 0x9f, 0xa2, 0x15, 0xbc, 0x03, 0x0f, 0x2a, 0xa4,
	0x65, 0x97, 0x49, 0xbb, 0xd1, 0xa4, 0xc4, 0x3a, 0x53, 0xcb, 0x06, 0x7e, 0x07, 0x0a, 0x94, 0x94,
	0x89, 0xdd, 0x22, 0xed, 0xe4, 0x76, 0xc5, 0x6a, 0x5a, 0xc8, 0x2c, 0x7e, 0x05, 0xdb, 0xb3, 0xb2,
	0x2e, 0x9d, 0xd4, 0xc8, 0x45, 0x5b, 0x77, 0x84, 0x56, 0xf0, 0x23, 0xc0, 0x56, 0x95, 0x12, 0xab,
	0xf2, 0x65, 0xb4, 0x43, 0x28, 0xa9, 0x20, 0x43, 0xae, 0x27, 0x8e, 0x44, 0x28, 0xad, 0x53, 0x64,
	0x16, 0x7b, 0xb7, 0xac, 0x2b, 0x55, 0xf0, 0x13, 0xd8, 0xb1, 0x6b, 0x2d, 0xab, 0x6a, 0x57, 0xda,
	0x8d, 0x73, 0x52, 0xb6, 0x4f, 0xec, 0xf2, 0xd8, 0x85, 0xec, 0x61, 0xbb, 0x49, 0xda, 0xcd, 0xfa,
	0x29, 0xa9, 0xb5, 0x29, 0xf9, 0xec, 0x73, 0x3b, 0xf4, 0xf1, 0x3f, 0x78, 0x2c, 0x4f, 0x14, 0x46,
	0xd1, 0x68, 0xd7, 0xea, 0xcd, 0xb6, 0x55, 0xad, 0xd6, 0x2f, 0x48, 0x05, 0x99, 0xc5, 0x73, 0xd8,
	0x9e, 0x95, 0x3d, 0x8c, 0x61, 0x33, 0x8a, 0xb7, 0x4c, 0x89, 0xd5, 0x24, 0x15, 0xb4, 0x82, 0x1f,
	0xc0, 0x46, 0xb4, 0x46, 0xbe, 0xb0, 0x1b, 0xcd, 0x06, 0x32, 0xb4, 0xa5, 0x13, 0xcb, 0xae, 0x4a,
	0x8b, 0x97, 0xab, 0x4a, 0x9a, 0x67, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xf0, 0xd5, 0x92,
	0x3c, 0x0f, 0x00, 0x00,
}
